#文件的主路径
main_path: "/root/CPUtest/llama/main"

#模型路径
model_path: "/root/CPUtest/llama/models/13B/ggml-model-q4_0.bin "

#线程数量
thread: 32

SSH:
  s6_32c:
    ip_address: 42.194.225.167
    username: root
    password: sztu2023!

instruction:
  1: Give three tips for staying healthy.

#  2: What are the three primary colors?
#
#  3: Describe the structure of an atom.
#
#  4: How can we reduce air pollution?
#
#  5: Describe a time when you had to make a difficult decision.
#
#  6: Look up the boiling point of water
#
#  7: What is the capital of France?
#
#  8: Write a short story in third person narration about a protagonist who has to make an important career decision.
#
#  9: Render a 3D model of a house
#
#  10: How did Julius Caesar die?

prompt: "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions."